services:
  backend:
    build:
      context: ${BACKEND_CONTEXT:-./back-end/demo/demo}
      dockerfile: Dockerfile
    container_name: backend-container
    ports:
      - "8081:8081"
    networks:
      - mynet

  frontend:
    build:
      context: ${FRONTEND_CONTEXT:-./FINANCIAL_APP/my-banking-app}
      dockerfile: Dockerfile
    container_name: frontend-container
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
