name: Compose CI (frontend build only)

on:
  push:
    branches: ["**"]
    paths:
      - "docker-compose.yml"
      - ".github/workflows/compose-ci.yml"
  pull_request:
    branches: ["**"]
    paths:
      - "docker-compose.yml"
      - ".github/workflows/compose-ci.yml"
  workflow_dispatch:

jobs:
  compose-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
      - name: "Checkout this repo (compose)"
        uses: actions/checkout@v4

      - name: "Checkout frontend repo"
        uses: actions/checkout@v4
        with:
          repository: ItsMePince/financial_app
          ref: main
          path: FINANCIAL_APP/my-banking-app

      - name: "Checkout backend repo"
        uses: actions/checkout@v4
        with:
          repository: ItsMePince/back-end
          ref: main
          path: back-end/demo/demo

      - name: "Preflight - verify directories exist"
        shell: bash
        run: |
          echo "PWD=$(pwd)"
          ls -R | head -n 100
          if [ ! -d FINANCIAL_APP/my-banking-app ]; then
            echo "missing FINANCIAL_APP/my-banking-app"; exit 1
          fi
          if [ ! -d back-end/demo/demo ]; then
            echo "missing back-end/demo/demo"; exit 1
          fi

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v3

      - name: "Validate docker-compose"
        run: docker compose -f "${{ github.workspace }}/docker-compose.yml" config

      - name: "Build frontend service"
        run: docker compose -f "${{ github.workspace }}/docker-compose.yml" --progress=plain build frontend
